### ISSUE TITLE
Document Kubernetes deployment procedure

### ISSUE THREAD

**Issue by jpolchlo** [azavea/noaa-hydro-data#106]
Following #69, there is a need to document in this repo the deployment procedure for this project.  Since there are unique requirements for the configuration of this project's infrastructure, this may require a NOAA deployment branch in [kubernetes-deployment](https://github.com/azavea/kubernetes-deployment).

**Comment by elizawallace** [comment]
This work will be offloaded to the [https://github.com/azavea/kubernetes-deployment](url) repository.
