### ISSUE TITLE
Upgrade pangeo base notebook version

### ISSUE THREAD

**Issue by jpolchlo** [azavea/noaa-hydro-data#114]
I've got a working configuration using an older Pangeo-provided base notebook (version 2022.05.18).  I've made an effort at bumping this version in the past, but it caused problems with the `jupyter_notebook_config.py` not being picked up, which blew up the `s3contents` configuration which is how we are currently storing our notebooks on S3.  I need to bring this up to date, since we are falling behind on python versions (currently on 3.9, ought to be on 3.10), among other things.

**Comment by elizawallace** [comment]
Current Jupyter environment is sufficient considering that we don't expect high usage.
