### ISSUE TITLE
Rechunk retrospective channel routing data

### ISSUE THREAD

**Issue by jpolchlo** [azavea/noaa-hydro-data#119]
As we have learned, the retrospective NWM data are stored in a Zarr file in time-major format—that is, it is chunked so that different time slices' data are spatially coherent in storage.  We've learned that this ordering of data makes queries on individual river reaches more time-consuming, and I've recently had some issues where the order of operations can result in some very crashy notebooks.

This issue, then, covers the creation of a rechunked version of the full channel routing dataset.

Connects #104 
Closes #26

**Comment by jpolchlo** [comment]
@rajadain @vlulla @elizawallace I'm assuming that there is a task in the proposal that associates with this work item?  I can't find one, though, and I'd like to connect this issue to that one.  Any ideas?  Or did we not have an entry in the proposal for producing a rechunked retro dataset?

**Comment by jpolchlo** [comment]
We had deferred this task in favor of #104, but it sounds like this should be somewhat quick to do, and if that assessment holds up, then we're probably best to just do this task and retrospectively figure out how much it cost.

**Comment by elizawallace** [comment]
Need to create cost estimate for the rechunking.
