### ISSUE TITLE
Task 1-4: Demonstrate the Water Budget Workflow

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#29]
Azavea will create a Jupyter Notebook to evaluate its ability to join NWM streamflow Parquet and gridded Zarr output for multiple HUCs to close the water budget. Results will be presented in interim and final project reports.

**Comment by jpolchlo** [comment]
Some information on the way to the solution for this task.

The water budget is the following accounting identity:
$$\frac{\mathrm{d}TWS}{\mathrm{d}t} \equiv P - R - ET$$
where $TWS$ is terrestrial water storage, $P$ is precipitation, $R$ is runoff, and $ET$ is evapotranspiration.  This is an identity, so it always holds, but our models and estimates of the quantities in the identity are imperfect.  The _closure_ of the water budget appears to be a reconciliation of the various terms on the way to a balanced budget.

We need to connect the terms of this equation to the variables in the NWM.  This will require some care to ensure that we are not double-counting any quantities.  Specific documentation for the model outputs has been hard to find, and seems to be written for seasoned practitioners, or at least not for neophytes.  The best I've encountered so far can be found [here](https://ral.ucar.edu/sites/default/files/public/WRFHydroV5_OutputVariableMatrix_V5.pdf).

**Comment by jpolchlo** [comment]
A useful document for learning about water budgets: https://water.usgs.gov/watercensus/AdHocComm/Background/WaterBudgets-FoundationsforEffectiveWater-ResourcesandEnvironmentalManagement.pdf

**Comment by elizawallace** [comment]
Meetings with local water planners indicate that the NWM isn't commonly used for this work. Instead, planners rely on local water gauges and data on withdrawals.
