### ISSUE TITLE
Saving subset of NWM runs out of memory

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#3]
To support benchmarking, I am trying to save a subset of NWM in Zarr and Parquet formats. The full size of the CHRTOUT portion is 4TB which is too big to work with. I would like to create a subset that is around 1 GB, but I am only able to save 10 MB without running out of memory. When working with a larger subset of the data, I run out of memory in the `save_nwm_sample` notebook when calling either of these lines:

```
df = df.set_index('feature_id')
df.to_parquet(parq_path)
```

**Comment by jpolchlo** [comment]
I wonder if this issue is still relevant.  I believe we have backed off of saving these to parquet, and #122 saves the full data as a rechunked zarr.
