### ISSUE TITLE
Task 2-3: Develop Metadata Catalog for NWM Predictions

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#33]
Under this task Azavea will evaluate and select a suitable metadata format for locating the required forecast datasets as part of the query process.

**Comment by elizawallace** [comment]
Possibly might be worthwhile to create a cache of Predictions data by appending new data to a zarr file.

**Comment by elizawallace** [comment]
Depends on K8s service that will add to combined Kerchunk file
