### ISSUE TITLE
Task 3-1: Develop NHDPlus Library for Python

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#35]
Azavea will develop an NHDPlus data access library for Python and publish it under an open source license to support a wider audience for its ongoing contribution and stewardship. The availability of this library will greatly simplify the use of NWM outputs by modelers in the Jupyter Notebook environment.

**Comment by rajadain** [comment]
Designing a library depends on the kinds of queries we'll have to run. Tasks 1 and 2 will inform that design.

**Comment by lewfish** [comment]
We should also see if HyRiver already has this functionality.

**Comment by rajadain** [comment]
In addition, it also pulls data from [NHD MR](https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer) and [NHDPlus HR](https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer) web services.
