### ISSUE TITLE
Task 3-2: Develop National Water Boundary Dataset Library for Python

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#36]
Similar to Task 3-1, Azavea will develop a data access and representation library for the National Water Boundary Dataset that simplifies the process of securing and querying the data in the Python Notebook environment.

**Comment by rajadain** [comment]
HyRiver can query the WaterData web service, which has support for querying HUC-8s and HUC-12s. No support for other levels of hydrologic units, unfortunately. But this may be enough.

Demo: https://gist.github.com/rajadain/34887c5f0564715acedfb437fc260342

**Comment by rajadain** [comment]
HyRiver is a wrapper around existing web services, and uses the [USGS Labs Geoserver](https://labs.waterdata.usgs.gov/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?1&filter=false) which only has HUC8 and HUC12 support. However, there is a [National Map ArcGIS Online instance](https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/) that supports HUC2 all the way to HUC16, which we could add support for in HyRiver, which would be a useful contribution. We should talk to Taher and other maintainers before we begin that process.
