### ISSUE TITLE
Task 4-1: Develop Automatic Conversion of NWM Predictions

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#39]
Azavea will develop a process to convert predictions and update the corresponding Zarr and Parquet encodings to support both the initial data conversion and incremental updates.

**Comment by lewfish** [comment]
After our May 3 stakeholder meeting, we learned that the NWM predictions are being archived on Google Cloud at https://console.cloud.google.com/marketplace/details/noaa-public/national-water-model. This means that our job is not to archive the predictions, but to transform them in useful ways. The most important transformation is to re-chunk to support more efficient access, but people also suggested aggregating spatially and temporally as potentially useful.

**Comment by elizawallace** [comment]
Completed with PR #132.
