### ISSUE TITLE
Find answers to questions about NHD and NWM

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#52]
There are two questions about NHD and NWM that came up when writing [this notebook](https://github.com/azavea/noaa-hydro-data/blob/master/src/notebooks/huc8_streamflow_query.ipynb) that couldn't be immediately answered. The questions can be found by searching for the string "question" when viewing the notebook. The goal is to run through this notebook and find the answers. This should also be a good exercise in learning about the datasets used on this project.

**Comment by vlulla** [comment]
> All CONUS model configurations provide streamflow for 2.7 million river reaches and other hydrologic information on 1km and 250m grids.
>                                               -- NOAA's Office of Water Prediction's [The National Water Model](https://water.noaa.gov/about/nwm)

It appears that the `nhdflowline` table in the NHDPlusV2 has extra rows which might not be included in the NWM model. This assumption is based on the observation that the NHDPlusV2 guide mentions that `Only flowlines with FlowDir="With Digitized" are used to define the surface water network used in the NHDPlus. All other flow lines are ignored by NHDPlus.` (on pg 160 under the description for `NHDFlowline` table in the [NHDPlus version 2 User Guide](https://www.nhdplus.com/NHDPlus/NHDPlusV2_documentation.php#NHDPlusV2%20User%20Guide) pdf).

This can be verified by the following postgresql query:

```sql
select replace(flowdir,' ','') flowdir, count(*) ncounts 
  from nhdflowline 
  group by rollup(replace(flowdir,' ','')) 
  order by flowdir;
+---------------+---------+
|    flowdir    | ncounts |
+---------------+---------+
| Uninitialized |  311005 |
| WithDigitized | 2724612 |
|               | 3035617 |
+---------------+---------+
(3 rows)
```
It is still not clear why the NWM datasets have about 2.77 million river reaches whereas the NHDPlusV2 has only 2.72 million flowlines!

**Comment by vlulla** [comment]
@lewfish do i need to look into this more thoroughly to close this issue?

**Comment by lewfish** [comment]
Meh, I guess it's not a question we really need an answer to so I wouldn't put more effort into it now and you can close it.

**Comment by vlulla** [comment]
Ok thanks!
