### ISSUE TITLE
Data are not public

### ISSUE THREAD

**Issue by rabernat** [azavea/noaa-hydro-data#79]
As @rajadain already noted to me in person, the test data are not public

```python
import s3fs
fs = s3fs.S3FileSystem(anon=True)
url = 's3://research-lf-dev/noaa/reformat-sample/streamflow-zarr/'
fs.ls(url)
# -> ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

If you can enable anon access, others can help debug the parquet vs. zarr mystery.

**Comment by lewfish** [comment]
Just made public copies of the Parquet and Zarr versions of our NWM test subets: `s3://azavea-noaa-hydro-data-public/esip-v0/nwm-subset-10y-parquet/` and `s3://azavea-noaa-hydro-data-public/esip-v0/nwm-subset.zarr/`

**Comment by rabernat** [comment]
Awesome, thanks @lewfish!

**Comment by jpolchlo** [comment]
@lewfish: Is this resolved, then?  Are there other actions to be taken here?

**Comment by lewfish** [comment]
I think the immediate issue is resolved. We should think about making a more formal release once we're happier with our Parquet results.
