### ISSUE TITLE
Write forum post about why we run out of RAM when doing benchmark queries

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#82]
We were only able to run the `benchmark_queries.ipynb`notebook after increasing worker memory to 4GB (from 2GB), but this is surprising since the chunk sizes were around 100 mb. We should read the documentation more closely to see why this might be the case, and/or write a forum post asking about this.

**Comment by elizawallace** [comment]
closing for now. Vijay lost the context for this. was happening in lead-up to ESIP conference. Justin - this may be a dask issue.
