### ISSUE TITLE
Write blog post on data reformatting experiments

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#86]

**Comment by vlulla** [comment]
I will have the first draft of the blog post with our findings, in google doc format, by end of Friday. Will invite @lewfish and @rajadain to coauthor the blog post with their thoughts and observations too!

**Comment by rajadain** [comment]
Blog post: https://www.azavea.com/blog/2022/09/22/benchmarking-zarr-and-parquet-data-retrieval-using-the-national-water-model-nwm-in-a-cloud-native-environment/
