### ISSUE TITLE
Open source ESIP experiment code

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#87]
Once we are satisfied with the Parquet results, we should update the documentation and make datasets public. We should make sure to update the URIs in the notebooks to use these public datasets. See https://github.com/azavea/noaa-hydro-data/tree/master/src/esip-2022-presentation

**Comment by jpolchlo** [comment]
This issue feels like a bit of a straggler.  I don't think there's been any further action on this for months, and the task may have lost currency.  This is also holding up the closing of #90.

**Comment by lewfish** [comment]
@vlulla I think this was supposed to be completed along with publishing the blog. Is this done? If not, should we do it now or is it too stale?

**Comment by vlulla** [comment]
@lewfish and @jpolchlo the ESIP experiment code is all in the notebooks. So, this can be closed.
