### ISSUE TITLE
Improve Parquet results from ESIP

### ISSUE THREAD

**Issue by lewfish** [azavea/noaa-hydro-data#94]

**Comment by vlulla** [comment]
I ran the benchmark, using a separate notebook (`s3://noaa-notebooks/vlulla/benchmark-using-wide-parquet.ipynb`), for the wide parquet and found that using a wide parquet did not really improve the numbers. The input/output for/from the above notebook are here:

- Wide parquet dataset: `s3://azavea-noaa-hydro-data/esip-experiments/datasets/reanalysis-chrtout/parquet/vl/wide-parquets-all-feature_ids/streamflow-1990-1999-consolidated-wide.parquet`
- Benchmark results: `s3://azavea-noaa-hydro-data/esip-experiments/benchmarks/vl/08-22-2022-with-wide-parquet.csv`
- Plot of the results: `s3://azavea-noaa-hydro-data/esip-experiments/plots/parquet/vl/08-22-2022-wide-parquets/parquet.png`

**Comment by rajadain** [comment]
Not pursuing this at this time.
